### ISSUE TITLE
Reunión de grupo inicial

### ISSUE THREAD

**Issue by luxor-g** [PRIS2/erudicion#1]
Reunión de grupo vía Discord para la repartición de tareas.

Miembros presentes:
- Aarón Blanco Álvarez
- Miguel Ángel Puertas Sánchez
- Ramón Ramos Tristán
- Francisco Javier Hernández Montoya
- Juan Pablo Grosso Tarazaga
- Alejo Martín Arias Filippo

**Comment by aaronblanco** [comment]
Completada con éxito.
