### ISSUE TITLE
Comprobar acceso de administrador al repo. En caso de no accesos avisar imaguila@ual.es

### ISSUE THREAD

**Issue by imaguila** [PRIS2/erudicion#4]

**Comment by aaronblanco** [comment]
Prueba completada con éxito aceptando los pull request.
![Captura de pantalla 2021-02-14 123648](https://user-images.githubusercontent.com/14028975/107875624-53e21100-6ec1-11eb-8df7-dc4c4909be38.png)

**Comment by imaguila** [comment]
Cambiad el estado de las tareas en el kanban del proyecto, para dar por finalizada la tarea
